name: rise-environment
channels:
- damianavila82
- conda-forge
dependencies:
- numpy
- scipy
- matplotlib
- rise
- mayavi
- notebook
- pip:
  - mne
  - https://api.github.com/repos/autoreject/autoreject/zipball/master
